// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9XKj7YW2xGQZ1fZQJZ3XY2xZqZXYZXYZ',
    appId: '1:116221288752838886007:web:abc123def456',
    messagingSenderId: '116221288752838886007',
    projectId: 'dijital-salon',
    authDomain: 'dijital-salon.firebaseapp.com',
    storageBucket: 'dijital-salon.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9XKj7YW2xGQZ1fZQJZ3XY2xZqZXYZXYZ',
    appId: '1:116221288752838886007:android:abc123def456',
    messagingSenderId: '116221288752838886007',
    projectId: 'dijital-salon',
    storageBucket: 'dijital-salon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9XKj7YW2xGQZ1fZQJZ3XY2xZqZXYZXYZ',
    appId: '1:116221288752838886007:ios:abc123def456',
    messagingSenderId: '116221288752838886007',
    projectId: 'dijital-salon',
    storageBucket: 'dijital-salon.appspot.com',
    iosBundleId: 'com.example.digimobilNew',
  );
}

